version: '3.8'
services:
  web:
    container_name: EmailMiddleware
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - "8011:8010"  # Mapping host's port 8081 to container's port 8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn src.wsgi:application --bind 0.0.0.0:8010"
    restart: always